### ISSUE TITLE
Favicon

### ISSUE THREAD

**Issue by lgarron** [adamcaudill/hstspreload.com#3]
It's great to have more services around the preload list, but I want to make sure the favicon for hstspreload.org is distinguishable from related sites; would you mind changing the one for hstspreload.com to something else?

**Comment by adamcaudill** [comment]
It'll be done this evening.

**Comment by adamcaudill** [comment]
Apologies for the delay @lgarron (had an issue with the laptop that had the SSH key for that server); this has been completed.

On a related note: Thanks for the good work you are doing; it's really appreciated.

**Comment by lgarron** [comment]
Thanks!
