### ISSUE TITLE
Firefox and Tor status incorrectly reported

### ISSUE THREAD

**Issue by bardiharborow** [adamcaudill/hstspreload.com#4]
https://hstspreload.com/api/v1/status/pinimg.com returns:

```json
{"domain":"pinimg.com","chrome":{"present":true,"include_subdomains":true,"last_updated":1503194464},"firefox":null,"tor":null}
```

`pinimg.com` is definitely preloaded in both [the stable list](https://hg.mozilla.org/releases/mozilla-release/raw-file/FIREFOX_55_0_2_RELEASE/security/manager/ssl/nsSTSPreloadList.inc) and [the ESR list](https://hg.mozilla.org/releases/mozilla-esr52/raw-file/FIREFOX_52_3_0esr_RELEASE/security/manager/ssl/nsSTSPreloadList.inc). `pinterest.com` has a similar issue.

**Comment by adamcaudill** [comment]
Thanks! Looks like changes were made to the file format, and I missed it. I've updated the load process and reloaded the data. That call now returns the following:

`{"domain":"pinimg.com","chrome":{"present":true,"include_subdomains":true,"last_updated":1503238625},"firefox":{"present":true,"include_subdomains":true,"last_updated":1503238681},"tor":{"present":true,"include_subdomains":true,"last_updated":1503239247}}`
