### ISSUE TITLE
TorBrowser data is years out of date

### ISSUE THREAD

**Issue by acohn** [adamcaudill/hstspreload.com#6]
Based on the links on the hstspreload.com website, and the /load/tor script, hstspreload.com is using a version of TorBrowser's preload list that was last updated in 2017. I'm not sure of a good programmatic way to get the git tag of the latest TorBrowser release. (The tag for the current release, which identifies itself in the about screen as "8.5.5 (based on Mozilla Firefox 60.9.0esr)" appears to be "tor-browser-60.9.0esr-8.5-2-build3")

TorBrowser appears not to be maintaining their own preload list, but instead taking snapshots of Mozilla's whenever they pull in a new ESR version of Firefox, so the TorBrowser preload list is of dubious utility IMO. But if you're offering it, it should be up to date.

FWIW, the TorBrowser 8.5.5 preload list is [here](https://gitweb.torproject.org/tor-browser.git/plain/security/manager/ssl/nsSTSPreloadList.inc?h=tor-browser-60.9.0esr-8.5-2-build3).

**Comment by adamcaudill** [comment]
Hi @acohn, apologies for taking so long to notice this issue. You are absolutely correct that it was bad practice - and I'm honestly not sure why I went that route when I wrote this. I've updated the script to correct this, and confirmed that it's loading new data correctly.

Thanks for pointing this out!
